/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Ordenar.OrdFeAsc;
import Ordenar.OrdFeDes;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Marco René Esquivel Juárez
 */
public class frmHistorial extends javax.swing.JFrame {

    /**
     * Creates new form frmHistorial
     */
    public DefaultTableModel mdlTabla;
    public DefaultTableModel mdlTabla2;

    public frmHistorial() {
        initComponents();
        this.mdlTabla = (DefaultTableModel) this.tblRelaciones.getModel();
        this.mdlTabla2 = (DefaultTableModel) this.tblProductos.getModel();
        cargarTabla1();
        this.txtMax.setText(Double.toString(maximo()));
        this.txtMin.setText(Double.toString(minimo()));
        this.txtTot.setText(Double.toString(sumatoria()));
        this.txtProm.setText(Double.toString(promedio()));
    }

    private void cargarTabla1() {
        this.mdlTabla.setRowCount(0);
        for (int j = 0; j < Parcial2POO.lR.size(); j++) {
            String[] registro = {
                Parcial2POO.lR.get(j).getCliente().getNombre() + " " + Parcial2POO.lR.get(j).getCliente().getApellido(),
                Parcial2POO.lR.get(j).getCliente().getDUI(),
                Parcial2POO.df.format(Parcial2POO.lR.get(j).getVenta().getFecha()),
                Double.toString(Parcial2POO.lR.get(j).getVenta().getMonto())
            };
            this.mdlTabla.addRow(registro);
        }
    }

    private void cargarTabla2() {
        this.mdlTabla2.setRowCount(0);
        int iRel = this.tblRelaciones.getSelectedRow();
        int n = Parcial2POO.lR.get(iRel).getVenta().getlF().size();

        for (int j = 0; j < n; j++) {
            String[] registro = {
                Parcial2POO.lR.get(iRel).getVenta().getlF().get(j).getNombre(),
                Double.toString(Parcial2POO.lR.get(iRel).getVenta().getlF().get(j).getPrecio()),
                Parcial2POO.lR.get(iRel).getVenta().getlF().get(j).getTipo(),
                Parcial2POO.df.format(Parcial2POO.lR.get(iRel).getVenta().getlF().get(j).caducidad()),
                Parcial2POO.lR.get(iRel).getVenta().getlF().get(j).getCod(),
                Integer.toString(Parcial2POO.lR.get(iRel).getVenta().getlF().get(j).getUnidades())
            };
            this.mdlTabla2.addRow(registro);
        }
    }
    
    private double minimo()
    {
       double min=0;
       if(Parcial2POO.lR.size()>0)
       {
           min=Parcial2POO.lR.get(0).getVenta().getMonto();
           for(int i=1; i<Parcial2POO.lR.size(); i++)
           {
               if(min>Parcial2POO.lR.get(i).getVenta().getMonto())
                   min=Parcial2POO.lR.get(i).getVenta().getMonto();
           }
       }
       return min;
    }
    
    private double maximo()
    {
        
       double max=0;
       if(Parcial2POO.lR.size()>0)
       {
           max=Parcial2POO.lR.get(0).getVenta().getMonto();
           for(int i=1; i<Parcial2POO.lR.size(); i++)
           {
               if(max<Parcial2POO.lR.get(i).getVenta().getMonto())
                   max=Parcial2POO.lR.get(i).getVenta().getMonto();
           }
       }
       return max;
    }
    
    private double promedio()
    {
        double prom=(this.sumatoria()/Parcial2POO.lR.size());
        prom*=100;
        prom= Math.round(prom);
        return (prom/100);
    }
    
    private double sumatoria()
    {
        double total=0;
        for(int i=0; i<Parcial2POO.lR.size(); i++)
        {
            total+= Parcial2POO.lR.get(i).getVenta().getMonto();
        }
        total*=100;
        total= Math.round(total);
        return (total/100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRelaciones = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnOrdFeA = new javax.swing.JButton();
        btnOrdFeD = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblProductos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtMax = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtProm = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtTot = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(new java.awt.Dimension(788, 613));
        jPanel1.setMinimumSize(new java.awt.Dimension(788, 613));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Historial de ventas");

        tblRelaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "DUI", "Fecha", "Monto"
            }
        ));
        tblRelaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblRelacionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblRelaciones);

        jLabel2.setText("DUI:");

        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Nom:");

        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton4.setText("Mostrar todo");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnOrdFeA.setBackground(new java.awt.Color(111, 198, 255));
        btnOrdFeA.setText("Ordenar fecha Asc");
        btnOrdFeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdFeAActionPerformed(evt);
            }
        });

        btnOrdFeD.setBackground(new java.awt.Color(255, 111, 111));
        btnOrdFeD.setText("Ordenar fecha Asc");
        btnOrdFeD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdFeDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 615, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jTextField1)
                                        .addComponent(jButton1)
                                        .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                                    .addComponent(jButton2)
                                    .addComponent(jButton4)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnOrdFeA)
                                    .addComponent(btnOrdFeD))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrdFeA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnOrdFeD)
                        .addGap(30, 30, 30))))
        );

        jButton3.setText("Regresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        tblProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Precio", "Tipo", "Caducidad", "Codigo", "Cant"
            }
        ));
        jScrollPane2.setViewportView(tblProductos);

        jLabel4.setText("Maximo:");

        jLabel5.setText("Minimo:");

        jLabel6.setText("Promedio:");

        jLabel7.setText("Total:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Estadisticas de ventas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMin)
                                    .addComponent(txtMax)
                                    .addComponent(txtProm)
                                    .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2)
                        .addGap(12, 12, 12)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtProm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtTot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton3)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 788, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 613, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        Parcial2POO p = new Parcial2POO();
        p.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (frmVenta.validarDUI(this.jTextField1.getText())) {
            this.mdlTabla.setRowCount(0);
            String busc = this.jTextField1.getText();
            for (int j = 0; j < Parcial2POO.lR.size(); j++) {
                if (Parcial2POO.lR.get(j).getCliente().getDUI().equals(busc)) {
                    String[] registro = {
                        Parcial2POO.lR.get(j).getCliente().getNombre() + " " + Parcial2POO.lR.get(j).getCliente().getApellido(),
                        Parcial2POO.lR.get(j).getCliente().getDUI(),
                        Parcial2POO.df.format(Parcial2POO.lR.get(j).getVenta().getFecha()),
                        Double.toString(Parcial2POO.lR.get(j).getVenta().getMonto())
                    };
                    this.mdlTabla.addRow(registro);
                }
            }
            this.jTextField1.setText("");
            this.jTextField2.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese el DUI que desea buscar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (!"".equals(this.jTextField2.getText())) {
            this.mdlTabla.setRowCount(0);
            String busc = this.jTextField2.getText().toUpperCase();
            for (int j = 0; j < Parcial2POO.lR.size(); j++) {
                if ((Parcial2POO.lR.get(j).getCliente().getNombre()+" "+Parcial2POO.lR.get(j).getCliente().getApellido()).equals(busc)) {
                    String[] registro = {
                        Parcial2POO.lR.get(j).getCliente().getNombre() + " " + Parcial2POO.lR.get(j).getCliente().getApellido(),
                        Parcial2POO.lR.get(j).getCliente().getDUI(),
                        Parcial2POO.df.format(Parcial2POO.lR.get(j).getVenta().getFecha()),
                        Double.toString(Parcial2POO.lR.get(j).getVenta().getMonto())
                    };
                    this.mdlTabla.addRow(registro);
                }
            }
            this.jTextField1.setText("");
            this.jTextField2.setText("");
        }else{
            JOptionPane.showMessageDialog(null, "Ingrese el nombre que desea buscar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        cargarTabla1();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnOrdFeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdFeAActionPerformed
        OrdFeAsc oFA = new OrdFeAsc();
        Parcial2POO.lR.sort(oFA);
        this.cargarTabla1();
    }//GEN-LAST:event_btnOrdFeAActionPerformed

    private void btnOrdFeDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdFeDActionPerformed
        OrdFeDes oFD = new OrdFeDes();
        Parcial2POO.lR.sort(oFD);
        this.cargarTabla1();
    }//GEN-LAST:event_btnOrdFeDActionPerformed

    private void tblRelacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblRelacionesMouseClicked
        this.cargarTabla2();
    }//GEN-LAST:event_tblRelacionesMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdFeA;
    private javax.swing.JButton btnOrdFeD;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    public javax.swing.JTable tblProductos;
    public javax.swing.JTable tblRelaciones;
    private javax.swing.JTextField txtMax;
    private javax.swing.JTextField txtMin;
    private javax.swing.JTextField txtProm;
    private javax.swing.JTextField txtTot;
    // End of variables declaration//GEN-END:variables
}
