/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Entidades.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Marco René Esquivel Juárez
 */
public class Parcial2POO extends javax.swing.JFrame {

    public static double dineroFarmacia = 500.00;
    public static ArrayList<Farmaco> lFar = new ArrayList<>();
    public static ArrayList<Relaciones> lR = new ArrayList<>();
    public static SimpleDateFormat df = new SimpleDateFormat("dd/MM/yyyy");
    public static SimpleDateFormat parser = new SimpleDateFormat("dd-MM-yyyy");
    public static int nAg = 3;
    public static int nAa = 3;
    public static int nAi = 3;
    public static int nAd = 3;

    public Parcial2POO() {
        initComponents();
        if (lFar.isEmpty()) {
            simularDatos();
        }

    }

    public static ArrayList<Farmaco> agregarAnalgesico(String nom, double pre, Date f, String cod, int cant, ArrayList<Farmaco> pLF) {
        Analgesico ag = new Analgesico(nom, pre, f, cod, cant);
        pLF.add(ag);
        return pLF;
    }

    public static ArrayList<Farmaco> agregarAntialergico(String nom, double pre, Date f, String cod, int cant, ArrayList<Farmaco> pLF) {
        Antialergico al = new Antialergico(nom, pre, f, cod, cant);
        pLF.add(al);
        return pLF;
    }

    public static ArrayList<Farmaco> agregarAntiinflamatorio(String nom, double pre, Date f, String cod, int cant, ArrayList<Farmaco> pLF) {
        Antiinflamatorio ai = new Antiinflamatorio(nom, pre, f, cod, cant);
        pLF.add(ai);
        return pLF;
    }

    public static ArrayList<Farmaco> agregarAntidepresivo(String nom, double pre, Date f, String cod, int cant, ArrayList<Farmaco> pLF) {
        Antidepresivo ad = new Antidepresivo(nom, pre, f, cod, cant);
        pLF.add(ad);
        return pLF;
    }

    public static void simularDatos() {
        try {
            //Analgesicos
            lFar = agregarAnalgesico("Acetaminofen", 1.75, parser.parse("07-12-2022"), "AG001", 100, lFar);
            lFar = agregarAnalgesico("Ibuprofeno", 2.50, parser.parse("03-02-2025"), "AG002", 50, lFar);
            lFar = agregarAnalgesico("Aspirina", 1.50, parser.parse("06-07-2022"), "AG003", 43, lFar);

            //Antialergicos
            lFar = agregarAntialergico("Zyrtec Allergy", 3.50, parser.parse("30-01-2022"), "AA001", 33, lFar);
            lFar = agregarAntialergico("Clarinex", 5.00, parser.parse("10-11-2024"), "AA002", 53, lFar);
            lFar = agregarAntialergico("Allegra Allergy", 4.15, parser.parse("09-12-2027"), "AA003", 20, lFar);

            //Antiinflamatorios
            lFar = agregarAntiinflamatorio("Cataflam", 3.15, parser.parse("03-06-2028"), "AI001", 50, lFar);
            lFar = agregarAntiinflamatorio("Voltaren XR", 1.05, parser.parse("07-12-2024"), "AI002", 60, lFar);
            lFar = agregarAntiinflamatorio("Nalfon", 6.75, parser.parse("05-10-2023"), "AI003", 10, lFar);

            //Antidepresivos
            lFar = agregarAntidepresivo("Prozac", 14.75, parser.parse("07-12-2022"), "AD001", 5, lFar);
            lFar = agregarAntidepresivo("Paxil", 34.50, parser.parse("27-04-2025"), "AD002", 10, lFar);
            lFar = agregarAntidepresivo("Lexapro", 26.25, parser.parse("07-12-2022"), "AD003", 20, lFar);
        } catch (ParseException ex) {
            Logger.getLogger(Parcial2POO.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(7, 118, 178));
        jLabel1.setText("Farmacia");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Realizar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Ver inventario");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Ver historial de ventas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(56, 56, 56)
                .addComponent(jButton2)
                .addGap(47, 47, 47)
                .addComponent(jButton3)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
        frmVenta fV = new frmVenta();
        fV.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        frmInventario fI = new frmInventario();
        fI.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        this.setVisible(false);
        frmHistorial fH = new frmHistorial();
        fH.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Parcial2POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Parcial2POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Parcial2POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Parcial2POO.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Parcial2POO().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
